#!/bin/bash
# Interactive Free Deployment Chooser
# Run: bash scripts/choose-free-deployment.sh

echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║   CCNA Platform - FREE Deployment Chooser          ║"
echo "║   Which platform should you use?                   ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

PS3='Choose your deployment platform (1-4): '
options=(
    "Railway (Easiest - 5 min) - FREE \$5/month credit"
    "Fly.io (Fastest - 5 min) - FREE \$5/month credit"
    "Oracle Cloud (Free Forever - 30 min) - FREE FOREVER"
    "Render (Free Tier - 10 min) - FREE but limited"
)

select opt in "${options[@]}"
do
    case $opt in
        "Railway (Easiest - 5 min) - FREE \$5/month credit")
            echo ""
            echo "═════════════════════════════════════════════════════"
            echo "🚀 RAILWAY DEPLOYMENT (5 MINUTES)"
            echo "═════════════════════════════════════════════════════"
            echo ""
            echo "1️⃣  Go to: https://railway.app"
            echo ""
            echo "2️⃣  Sign up with GitHub"
            echo ""
            echo "3️⃣  Create New Project → Import from GitHub"
            echo ""
            echo "4️⃣  Select this repository"
            echo ""
            echo "5️⃣  Click 'Deploy'"
            echo ""
            echo "6️⃣  Railway will automatically:"
            echo "   ✓ Detect Node.js app"
            echo "   ✓ Create PostgreSQL database"
            echo "   ✓ Deploy everything"
            echo "   ✓ Give you a live URL"
            echo ""
            echo "📊 Your FREE $5/month credit covers:"
            echo "   ✓ All compute"
            echo "   ✓ PostgreSQL database"
            echo "   ✓ All bandwidth"
            echo ""
            echo "⏱️  Total time: ~5 minutes"
            echo "💰 Cost: $0/month"
            echo ""
            echo "👉 Go to: https://railway.app"
            echo ""
            break
            ;;
        "Fly.io (Fastest - 5 min) - FREE \$5/month credit")
            echo ""
            echo "═════════════════════════════════════════════════════"
            echo "⚡ FLY.IO DEPLOYMENT (5 MINUTES)"
            echo "═════════════════════════════════════════════════════"
            echo ""
            echo "1️⃣  Install Fly CLI:"
            echo "   curl -L https://fly.io/install.sh | sh"
            echo ""
            echo "2️⃣  Login:"
            echo "   flyctl auth login"
            echo ""
            echo "3️⃣  Deploy from project root:"
            echo "   cd websitepractice"
            echo "   flyctl deploy -a ccna-platform"
            echo ""
            echo "4️⃣  Open your app:"
            echo "   flyctl open -a ccna-platform"
            echo ""
            echo "✨ Fly.io will automatically:"
            echo "   ✓ Build your Docker images"
            echo "   ✓ Create PostgreSQL database"
            echo "   ✓ Deploy globally"
            echo "   ✓ Set up SSL/HTTPS"
            echo ""
            echo "📊 Your FREE \$5/month credit covers:"
            echo "   ✓ Database & compute"
            echo "   ✓ All traffic"
            echo "   ✓ Global CDN"
            echo ""
            echo "⏱️  Total time: ~5 minutes"
            echo "💰 Cost: \$0/month"
            echo "🚀 Performance: Excellent (global edge network)"
            echo ""
            echo "👉 Next command:"
            echo "   curl -L https://fly.io/install.sh | sh"
            echo ""
            break
            ;;
        "Oracle Cloud (Free Forever - 30 min) - FREE FOREVER")
            echo ""
            echo "═════════════════════════════════════════════════════"
            echo "☁️  ORACLE CLOUD DEPLOYMENT (30 MINUTES)"
            echo "═════════════════════════════════════════════════════"
            echo ""
            echo "1️⃣  Create Oracle Account (FREE):"
            echo "   https://oracle.com/cloud/free"
            echo "   (No credit card needed after free trial)"
            echo ""
            echo "2️⃣  Create Compute Instance:"
            echo "   - Dashboard → Compute → Instances"
            echo "   - Image: Ubuntu 22.04"
            echo "   - Shape: VM.Standard.A1.Flex (ARM - ALWAYS FREE)"
            echo "   - OCPUs: 2, RAM: 12GB"
            echo "   - Download SSH key"
            echo ""
            echo "3️⃣  SSH into VM:"
            echo "   chmod 600 your-ssh-key.pem"
            echo "   ssh -i your-ssh-key.pem ubuntu@YOUR_IP"
            echo ""
            echo "4️⃣  Install Docker:"
            echo "   curl -fsSL https://get.docker.com -o get-docker.sh"
            echo "   sudo sh get-docker.sh"
            echo "   sudo usermod -aG docker \$USER"
            echo "   newgrp docker"
            echo ""
            echo "5️⃣  Deploy:"
            echo "   git clone YOUR_REPO"
            echo "   cd websitepractice"
            echo "   chmod +x scripts/deploy-docker.sh"
            echo "   ./scripts/deploy-docker.sh build"
            echo "   ./scripts/deploy-docker.sh start"
            echo ""
            echo "6️⃣  Access:"
            echo "   http://YOUR_PUBLIC_IP"
            echo ""
            echo "✨ What you get (COMPLETELY FREE FOREVER):"
            echo "   ✓ 2x ARM CPU cores"
            echo "   ✓ 12GB total RAM"
            echo "   ✓ 20GB MySQL database"
            echo "   ✓ 250GB object storage"
            echo "   ✓ NO expiration date"
            echo "   ✓ NO automatic charges"
            echo ""
            echo "⏱️  Total time: ~30 minutes (mostly setup)"
            echo "💰 Cost: \$0/month, FOREVER"
            echo "📊 Resources: Enough for 10,000+ concurrent users"
            echo ""
            echo "👉 Start at: https://oracle.com/cloud/free"
            echo ""
            break
            ;;
        "Render (Free Tier - 10 min) - FREE but limited")
            echo ""
            echo "═════════════════════════════════════════════════════"
            echo "🎨 RENDER DEPLOYMENT (10 MINUTES)"
            echo "═════════════════════════════════════════════════════"
            echo ""
            echo "1️⃣  Go to: https://render.com"
            echo ""
            echo "2️⃣  Sign up with GitHub"
            echo ""
            echo "3️⃣  Create Web Service"
            echo "   - Select this repository"
            echo "   - Name: ccna-platform"
            echo "   - Build: npm install && npm run build"
            echo "   - Start: npm start"
            echo ""
            echo "4️⃣  Add PostgreSQL database"
            echo ""
            echo "5️⃣  Click 'Deploy'"
            echo ""
            echo "⚠️  FREE TIER LIMITATIONS:"
            echo "   - App stops after 15 minutes of inactivity"
            echo "   - Slower performance (shared resources)"
            echo "   - 100MB database limit"
            echo "   - Slower cold starts"
            echo ""
            echo "💡 Better options:"
            echo "   → Railway: Better performance, same price"
            echo "   → Fly.io: Best performance, same price"
            echo "   → Oracle: Free forever with Render's performance"
            echo ""
            echo "⏱️  Total time: ~10 minutes"
            echo "💰 Cost: \$0/month"
            echo "🐌 Performance: Slow"
            echo ""
            echo "👉 Go to: https://render.com"
            echo "   (Recommended: Use Railway or Fly.io instead)"
            echo ""
            break
            ;;
        *) echo "Invalid option. Try again.";;
    esac
done

echo ""
echo "═════════════════════════════════════════════════════"
echo "📚 NEED MORE HELP?"
echo "═════════════════════════════════════════════════════"
echo ""
echo "For detailed comparison:"
echo "  → See: free.md"
echo ""
echo "For detailed guides:"
echo "  → See: FREE_DEPLOYMENT.md"
echo ""
echo "For quick step-by-step:"
echo "  → See: FREE_DEPLOYMENT_QUICK.md"
echo ""
echo "═════════════════════════════════════════════════════"
echo ""
echo "🎉 YOUR APP WILL BE RUNNING FOR FREE IN 5-30 MINUTES!"
echo ""
